#!/bin/bash

# Blog Creator Flow Diagrams Export Script
# This script helps you export all the Mermaid diagrams

echo "🚀 Blog Creator Flow Diagrams Export Helper"
echo "=========================================="
echo ""

echo "📁 Files created:"
echo "1. BLOG_CREATOR_FLOW_DIAGRAMS.md - Complete documentation with all diagrams"
echo "2. diagrams/01-frontend-user-journey.md"
echo "3. diagrams/02-blog-generation-process.md"
echo "4. diagrams/03-backend-api-processing.md"
echo "5. diagrams/04-strategic-planning-flow.md"
echo "6. diagrams/05-topic-recommendations-flow.md"
echo "7. diagrams/06-result-view-actions.md"
echo "8. diagrams/07-data-flow-architecture.md"
echo "9. diagrams/08-error-handling-fallbacks.md"
echo "10. diagrams/09-state-management-flow.md"
echo "11. diagrams/10-component-interaction-flow.md"
echo "12. diagrams/11-api-endpoints-overview.md"
echo ""

echo "📋 Export Instructions:"
echo "======================"
echo ""
echo "🖼️  For PNG/SVG/PDF Export:"
echo "1. Copy any diagram code (between \`\`\`mermaid and \`\`\`)"
echo "2. Go to https://mermaid.live/"
echo "3. Paste the code in the editor"
echo "4. Click 'Export' and choose format"
echo ""
echo "📚 For Documentation:"
echo "- Use the .md files directly in GitHub/GitLab (they render Mermaid)"
echo "- Copy to documentation platforms that support Mermaid"
echo ""
echo "🎯 For Presentations:"
echo "- Export as SVG for best quality"
echo "- Import into PowerPoint, Keynote, or other presentation software"
echo ""
echo "✅ All diagrams are ready for export!"
echo ""
echo "💡 Pro tip: You can also use the Mermaid CLI for batch export:"
echo "   npm install -g @mermaid-js/mermaid-cli"
echo "   mmdc -i diagram.md -o diagram.png" 