version: '3.8'

services:
  server:
    build: .
    ports:
      - "3001:10000"
    environment:
      - NODE_ENV=development
      - PORT=10000
      - FRONTEND_URL=http://localhost:3000
      - NVIDIA_API_KEY=${NVIDIA_API_KEY}
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:10000/api/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: MongoDB for development
  mongodb:
    image: mongo:6
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=reviewgen
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

volumes:
  mongodb_data: 