name: Deploy Server

on:
  push:
    branches: [ development, main ]
    paths:
      - 'server/**'
  pull_request:
    branches: [ development, main ]
    paths:
      - 'server/**'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: server/package-lock.json
    
    - name: Install dependencies
      run: |
        cd server
        npm ci
    
    - name: Run tests
      run: |
        cd server
        npm test
      env:
        NVIDIA_API_KEY: ${{ secrets.NVIDIA_API_KEY }}

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/development' || github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: server/package-lock.json
    
    - name: Install dependencies
      run: |
        cd server
        npm ci
    
    - name: Deploy to Render
      env:
        RENDER_TOKEN: ${{ secrets.RENDER_TOKEN }}
        RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
      run: |
        # This is a placeholder for Render deployment
        # You'll need to set up Render deployment separately
        echo "Deploying to Render..."
        echo "Service ID: $RENDER_SERVICE_ID"
    
    - name: Deploy to Railway
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      run: |
        # This is a placeholder for Railway deployment
        # You'll need to set up Railway deployment separately
        echo "Deploying to Railway..."
    
    - name: Deploy to Heroku
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
      run: |
        # This is a placeholder for Heroku deployment
        # You'll need to set up Heroku deployment separately
        echo "Deploying to Heroku..."
        echo "App Name: $HEROKU_APP_NAME" 